### ISSUE TITLE
Error: Unknown function default_content

### ISSUE THREAD

**Issue by quentinsikana** [example42/puppet-mariadb#10]
Hi here !

I'm using your module on a Vagrant box based on Debian 8.
After a simple `include mariadb` in my puppet file, I get the following error message:
```
Error: Unknown function default_content at /etc/puppet/modules/mariadb/manifests/init.pp:80
```

When I look into this file, the error comes from this line : 
```
$manage_config_file_content = default_content($config_file_content, $config_file_template)
```

And I don't see any definition for this `default_content()` function.

Any clue?

**Comment by alvagante** [comment]
Oh, you need to install the https://github.com/voxpupuli/puppet-extlib module which provides that function.
Have to fix the metadata.json file for dependencies
