### ISSUE TITLE
source.list.d file is not created

### ISSUE THREAD

**Issue by mortzel** [example42/puppet-mariadb#9]
Getting following Error when using this module.
`Error: Failed to apply catalog: Could not find dependent Exec[apt_update] for File[/etc/apt/sources.list.d/mariadb.list] at /etc/puppet/modules/apt/manifests/setting.pp:63`

Puppet Version: 3.4.3-1
Distro: Ubuntu 14.04/12.04

**Comment by alvagante** [comment]
You need example42 apt module (but it might wok also with puppetlabs' apt module).
Alternatively manage the repos with a custom class passed via the parameter repo_class of the mariadb class
